version: '3'
services:
  blog:
    build: blog/.
    ports:
      - "5000:5000"
  mysql:
    image: "mysql:latest"
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_prod