"""Add title to blog

Revision ID: 407172ffa48d
Revises: f707489fba45
Create Date: 2020-05-09 13:05:05.421465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407172ffa48d'
down_revision = 'f707489fba45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
