"""Add add_date and update_date to blog

Revision ID: 4210429aa32c
Revises: 407172ffa48d
Create Date: 2020-05-12 21:28:33.022009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4210429aa32c'
down_revision = '407172ffa48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('add_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('blog', sa.Column('update_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'update_date')
    op.drop_column('blog', 'add_date')
    # ### end Alembic commands ###
