"""Add blog model

Revision ID: b52485ef32f5
Revises:
Create Date: 2020-05-16 15:57:08.370411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52485ef32f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_names', sa.String(length=300), nullable=True),
    sa.Column('cooperators', sa.String(length=200), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('add_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
