"""Init model

Revision ID: c75a46c3df5c
Revises: e293059122fc
Create Date: 2020-06-17 21:31:58.969776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75a46c3df5c'
down_revision = 'e293059122fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('countries', sa.Text(), nullable=True))
    op.drop_column('blog', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('blog', 'countries')
    # ### end Alembic commands ###
