"""Initial migration.

Revision ID: f707489fba45
Revises: 
Create Date: 2020-05-09 13:02:17.645260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f707489fba45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('blog', 'views',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'views',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('blog', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
