version: '3'

services:
  account:
    build: .
    command: gunicorn project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgres:10"
    environment:
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCOUNT_POSTGRES_DB}
