version: '3'

services:
  sut:
    build: .
    command: netstat -tulpn | grep LISTEN
    environment:
      BLOG_SQL_TESTING: mysql://root:root@db:3307/blog_test
    depends_on:
      - db
  db:
    image: "mysql:latest"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_test
