apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: portfolio-gui
  name: portfolio-gui
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-gui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portfolio-gui
    spec:
      containers:
      - image: mtesluk/portfolio-gui
        name: demo-v1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: portfolio-gui
  name: portfolio-gui
  namespace: portfolio
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portfolio-gui
  type: ClusterIP
status:
  loadBalancer: {}